# Keras 
[Keras with TensorFlow Course - Python Deep Learning and Neural Networks for Beginners Tutorial](https://www.youtube.com/watch?v=qFJeN9V1ZsI&t=4527s)


In [1]:
!pip install tensorflow -q


/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(


In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, BatchNormalization, Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler


2022-10-29 13:07:47.477025: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-29 13:07:50.357845: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-29 13:07:50.357917: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-29 13:07:50.674936: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-29 13:07:58.569791: W tensorflow/stream_executor/platform/de

In [3]:

# DATA SET GENERATION
train_labels = []
train_samples= []

# total 2100 candidates 

for i in range(50):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)# 1 for sideeffect

    random_older= randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)# 0 for not sideeffect


for i in range(1000):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)# 1 for sideeffect

    random_older= randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)# 0 for not sideeffect




In [4]:
for i in range(0,len(train_labels)):
    print(train_samples[i],train_labels[i])

38 1
66 0
43 1
92 0
23 1
100 0
32 1
84 0
59 1
69 0
17 1
81 0
14 1
69 0
48 1
100 0
30 1
67 0
28 1
71 0
23 1
89 0
52 1
94 0
45 1
67 0
42 1
82 0
44 1
76 0
46 1
72 0
19 1
65 0
38 1
85 0
21 1
89 0
18 1
69 0
57 1
88 0
59 1
89 0
29 1
74 0
46 1
68 0
16 1
76 0
59 1
94 0
47 1
95 0
50 1
82 0
25 1
67 0
50 1
99 0
16 1
91 0
52 1
75 0
30 1
71 0
41 1
97 0
53 1
66 0
54 1
72 0
49 1
75 0
43 1
72 0
63 1
71 0
31 1
65 0
18 1
84 0
20 1
92 0
23 1
68 0
53 1
92 0
58 1
85 0
36 1
82 0
21 1
86 0
40 1
78 0
33 1
91 0
60 1
87 0
20 0
99 1
39 0
69 1
20 0
84 1
36 0
98 1
64 0
87 1
46 0
98 1
45 0
71 1
62 0
71 1
18 0
78 1
50 0
82 1
21 0
96 1
19 0
97 1
36 0
73 1
52 0
73 1
33 0
67 1
62 0
74 1
44 0
91 1
39 0
96 1
13 0
89 1
57 0
98 1
38 0
90 1
58 0
80 1
26 0
67 1
63 0
72 1
22 0
86 1
47 0
74 1
25 0
77 1
35 0
96 1
22 0
71 1
19 0
69 1
55 0
74 1
17 0
82 1
23 0
78 1
36 0
94 1
58 0
87 1
36 0
83 1
57 0
93 1
42 0
84 1
62 0
87 1
36 0
87 1
16 0
70 1
29 0
91 1
50 0
69 1
60 0
100 1
38 0
74 1
31 0
66 1
56 0
67 1
47 0
100 1
29 0
79 1
20 0
7

## Preporcessing Data

In [5]:
#convert to np array
train_labels=np.array(train_labels)
train_samples=np.array(train_samples)

# pre shuffle samples
train_labels, train_samples=shuffle(train_labels, train_samples)

In [6]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))


scaled_train_samples

array([[0.51724138],
       [0.64367816],
       [0.85057471],
       ...,
       [0.90804598],
       [0.08045977],
       [0.20689655]])

# Create NN

In [7]:
model= Sequential([
    Dense(units=16,input_shape=(1,),activation='relu'),
    Dense(units=32,activation='relu'),
    Dense(units=2,activation='softmax'),
])

2022-10-29 13:08:10.745268: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-29 13:08:10.745331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DrPrateek): /proc/driver/nvidia/version does not exist
2022-10-29 13:08:10.792452: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
# model.save('./modkl')
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


# Training On Data

In [9]:
model.compile(optimizer=Adam(learning_rate=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [10]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
210/210 - 2s - loss: 0.6520 - accuracy: 0.5767 - 2s/epoch - 11ms/step
Epoch 2/30
210/210 - 0s - loss: 0.6146 - accuracy: 0.6790 - 372ms/epoch - 2ms/step
Epoch 3/30
210/210 - 0s - loss: 0.5817 - accuracy: 0.7410 - 387ms/epoch - 2ms/step
Epoch 4/30
210/210 - 0s - loss: 0.5485 - accuracy: 0.7724 - 333ms/epoch - 2ms/step
Epoch 5/30
210/210 - 0s - loss: 0.5153 - accuracy: 0.8052 - 365ms/epoch - 2ms/step
Epoch 6/30
210/210 - 0s - loss: 0.4834 - accuracy: 0.8348 - 331ms/epoch - 2ms/step
Epoch 7/30
210/210 - 0s - loss: 0.4533 - accuracy: 0.8490 - 308ms/epoch - 1ms/step
Epoch 8/30
210/210 - 0s - loss: 0.4257 - accuracy: 0.8638 - 395ms/epoch - 2ms/step
Epoch 9/30
210/210 - 0s - loss: 0.4007 - accuracy: 0.8776 - 289ms/epoch - 1ms/step
Epoch 10/30
210/210 - 0s - loss: 0.3782 - accuracy: 0.8910 - 296ms/epoch - 1ms/step
Epoch 11/30
210/210 - 0s - loss: 0.3590 - accuracy: 0.9014 - 322ms/epoch - 2ms/step
Epoch 12/30
210/210 - 0s - loss: 0.3428 - accuracy: 0.9076 - 258ms/epoch - 1ms/step
Epo

In [11]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2,validation_split=.1)

Epoch 1/30
189/189 - 0s - loss: 0.2559 - accuracy: 0.9381 - val_loss: 0.2747 - val_accuracy: 0.9238 - 478ms/epoch - 3ms/step
Epoch 2/30
189/189 - 0s - loss: 0.2549 - accuracy: 0.9381 - val_loss: 0.2735 - val_accuracy: 0.9238 - 334ms/epoch - 2ms/step
Epoch 3/30
189/189 - 0s - loss: 0.2539 - accuracy: 0.9407 - val_loss: 0.2724 - val_accuracy: 0.9238 - 324ms/epoch - 2ms/step
Epoch 4/30
189/189 - 0s - loss: 0.2530 - accuracy: 0.9381 - val_loss: 0.2713 - val_accuracy: 0.9238 - 229ms/epoch - 1ms/step
Epoch 5/30
189/189 - 0s - loss: 0.2521 - accuracy: 0.9413 - val_loss: 0.2703 - val_accuracy: 0.9238 - 206ms/epoch - 1ms/step
Epoch 6/30
189/189 - 0s - loss: 0.2513 - accuracy: 0.9439 - val_loss: 0.2696 - val_accuracy: 0.9238 - 209ms/epoch - 1ms/step
Epoch 7/30
189/189 - 0s - loss: 0.2508 - accuracy: 0.9413 - val_loss: 0.2686 - val_accuracy: 0.9238 - 231ms/epoch - 1ms/step
Epoch 8/30
189/189 - 0s - loss: 0.2501 - accuracy: 0.9402 - val_loss: 0.2678 - val_accuracy: 0.9381 - 173ms/epoch - 915us/ste

# predict

In [12]:

# DATA SET GENERATION
test_labels = []
test_samples= []

# total 2100 candidates 

for i in range(50):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)# 1 for sideeffect

    random_older= randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)# 0 for not sideeffect


for i in range(1000):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)# 1 for sideeffect

    random_older= randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)# 0 for not sideeffect


test_samples=np.array(test_samples)
test_labels=np.array(test_labels)
test_samples,test_labels=shuffle(test_samples,test_labels)

scaled_test_samples=scaler.fit_transform(test_samples.reshape(-1,1))

# scaled_text_samples=scaler.fit_transform(x=test_samples,batch_size=10,verbose=1)

In [13]:
predictions= model.predict(x=scaled_test_samples,batch_size=10,verbose=0)

In [14]:
# for i in predictions:
#     print(i)

rounded_predictions=np.argmax(predictions,axis=-1)
for i in range(0,len(rounded_predictions)):
    print(test_samples[i],rounded_predictions[i])

79 1
25 0
32 0
50 0
82 1
91 1
43 0
54 0
28 0
58 0
74 1
99 1
53 0
52 0
84 1
100 1
18 0
80 1
42 0
36 0
39 0
77 1
27 0
39 0
20 0
60 0
84 1
77 1
44 0
87 1
19 0
15 0
80 1
40 0
90 1
32 0
51 0
33 0
60 0
52 0
85 1
64 1
82 1
40 0
98 1
26 0
94 1
79 1
75 1
100 1
57 0
68 1
37 0
71 1
19 0
57 0
74 1
95 1
86 1
63 0
95 1
35 0
90 1
96 1
69 1
20 0
96 1
80 1
44 0
20 0
56 0
34 0
87 1
36 0
92 1
75 1
37 0
49 0
25 0
60 0
59 0
77 1
86 1
97 1
18 0
100 1
63 0
46 0
99 1
87 1
83 1
43 0
70 1
91 1
64 1
34 0
56 0
68 1
31 0
98 1
26 0
43 0
31 0
72 1
87 1
57 0
22 0
54 0
42 0
49 0
24 0
58 0
62 0
14 0
78 1
64 1
17 0
68 1
14 0
75 1
26 0
56 0
26 0
89 1
41 0
90 1
94 1
36 0
28 0
14 0
68 1
39 0
73 1
18 0
97 1
76 1
28 0
35 0
64 1
88 1
74 1
34 0
51 0
54 0
44 0
92 1
80 1
21 0
92 1
51 0
96 1
21 0
73 1
59 0
34 0
25 0
13 0
31 0
73 1
99 1
23 0
91 1
84 1
42 0
68 1
15 0
40 0
95 1
37 0
20 0
80 1
37 0
65 1
27 0
60 0
84 1
16 0
82 1
85 1
32 0
62 0
87 1
83 1
78 1
55 0
83 1
97 1
28 0
39 0
61 0
76 1
71 1
66 1
16 0
90 1
85 1
58 0
40 0
92 1
87

# Confusion Matrix 

In [15]:
def confusionMatrix(orignal,prediction):
    cm=[[0,0],[0,0]]
    for i in range(0,len(orignal)):
        a= orignal[i]
        b=prediction[i]
        for x in [0,1]:
            for y in [0,1]:
                if a==x:
                    if b==y:
                        cm[x][y]+=1

    def plotCm(cm):
        pass


    plotCm(cm)
    return cm



cm=confusionMatrix(test_labels,rounded_predictions)
cm

[[979, 71], [50, 1000]]

# Save Model

In [16]:
import os
modelFilename="savedModle/medicalTrial.h5"
if os.path.isfile(modelFilename) is False:
    model.save(modelFilename)

In [17]:
from tensorflow.keras.models import load_model

newModel=load_model(modelFilename)
newModel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [18]:
newModel.get_weights()

[array([[ 0.7679544 , -0.3112032 ,  0.31227753, -0.14031768, -0.15540323,
         -0.03012776, -0.09825817, -0.25913218, -0.4552618 ,  0.20721169,
          0.04051489,  0.57031876,  0.42887068,  0.37723556, -0.19262823,
         -0.5767098 ]], dtype=float32),
 array([-0.15568447,  0.        , -0.13663937,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.09981668,
         0.20820671, -0.18135379,  0.11828248, -0.14080824,  0.        ,
         0.        ], dtype=float32),
 array([[ 4.99551058e-01,  1.30099311e-01, -2.27324784e-01,
         -4.90881801e-02,  2.68823653e-01, -1.27747178e-01,
         -2.44221181e-01,  3.96262228e-01, -4.04223323e-01,
         -3.57338220e-01, -4.57180142e-01,  6.35967255e-02,
          4.67240453e-01,  2.42485046e-01,  3.03201020e-01,
          2.46710777e-01,  4.28493708e-01, -1.45855516e-01,
          1.60658583e-01, -2.80374408e-01,  3.86377573e-01,
         -3.59820724e-01,  5.02546988e-02, -2.44706392e-01,
 

In [19]:
newModel.optimizer

In [20]:
from tensorflow.keras.models import model_from_yaml,model_from_json
yamlString=newModel.to_json()
yamlString


modelFromJson=model_from_json(yamlString)
modelFromJson.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [21]:
# newModel.save_weights("modelWeight/weight.h5")
model.get_weights()
model.save_weights("weights.h5")