# Keras 
[Keras with TensorFlow Course - Python Deep Learning and Neural Networks for Beginners Tutorial](https://www.youtube.com/watch?v=qFJeN9V1ZsI&t=4527s)


In [8]:
!pip install tensorflow -q


In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, BatchNormalization, Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler


In [15]:

# DATA SET GENERATION
train_labels = []
train_samples= []

# total 2100 candidates 

for i in range(50):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)# 1 for sideeffect

    random_older= randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)# 0 for not sideeffect


for i in range(1000):
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)# 1 for sideeffect

    random_older= randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)# 0 for not sideeffect




In [20]:
for i in range(0,len(train_labels)):
    print(train_samples[i],train_labels[i])

36 1
84 0
57 1
83 0
58 1
72 0
27 1
73 0
42 1
65 0
52 1
100 0
47 1
70 0
62 1
85 0
16 1
93 0
42 1
71 0
30 1
78 0
57 1
77 0
43 1
72 0
15 1
70 0
15 1
66 0
28 1
78 0
24 1
76 0
39 1
79 0
57 1
90 0
45 1
69 0
16 1
93 0
46 1
77 0
64 1
69 0
35 1
79 0
57 1
99 0
34 1
69 0
51 1
66 0
38 1
94 0
25 1
65 0
35 1
82 0
44 1
79 0
16 1
84 0
26 1
67 0
52 1
90 0
61 1
74 0
53 1
76 0
43 1
75 0
30 1
76 0
43 1
71 0
22 1
93 0
31 1
83 0
59 1
85 0
30 1
67 0
21 1
65 0
49 1
65 0
51 1
94 0
54 1
66 0
31 1
65 0
32 1
87 0
52 1
76 0
36 0
76 1
20 0
86 1
39 0
86 1
42 0
68 1
55 0
97 1
26 0
77 1
27 0
85 1
20 0
66 1
15 0
70 1
57 0
97 1
46 0
74 1
50 0
96 1
43 0
76 1
23 0
76 1
17 0
91 1
43 0
73 1
29 0
75 1
36 0
96 1
50 0
93 1
61 0
82 1
64 0
76 1
48 0
65 1
31 0
81 1
45 0
98 1
32 0
86 1
45 0
74 1
26 0
82 1
21 0
85 1
47 0
70 1
40 0
72 1
23 0
65 1
17 0
72 1
57 0
65 1
44 0
94 1
37 0
67 1
58 0
94 1
54 0
91 1
42 0
90 1
38 0
94 1
23 0
81 1
38 0
67 1
60 0
83 1
40 0
82 1
33 0
73 1
35 0
99 1
18 0
78 1
48 0
69 1
55 0
79 1
16 0
79 1
25 0
73 1

## Preporcessing Data

In [23]:
#convert to np array
train_labels=np.array(train_labels)
train_samples=np.array(train_samples)

# pre shuffle samples
train_labels, train_samples=shuffle(train_labels, train_samples)

In [27]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))


scaled_train_samples

array([[0.91954023],
       [0.4137931 ],
       [0.59770115],
       ...,
       [0.90804598],
       [0.85057471],
       [0.01149425]])

# Create NN

In [28]:
model= Sequential([
    Dense(units=16,input_shape=(1,),activation='relu'),
    Dense(units=32,activation='relu'),
    Dense(units=2,activation='softmax'),
])

2022-10-27 13:42:09.072617: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-27 13:42:09.073209: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-27 13:42:09.073354: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-10-27 13:42:09.073481: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-10-27 13:42:09.129146: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [36]:
# model.save('./modkl')
model.summary()


INFO:tensorflow:Assets written to: ./modkl/assets
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


# Training On Data

In [38]:
model.compile(optimizer=Adam(learning_rate=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [42]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
210/210 - 1s - loss: 0.2621 - accuracy: 0.9324 - 671ms/epoch - 3ms/step
Epoch 2/30
210/210 - 0s - loss: 0.2606 - accuracy: 0.9343 - 358ms/epoch - 2ms/step
Epoch 3/30
210/210 - 0s - loss: 0.2590 - accuracy: 0.9352 - 371ms/epoch - 2ms/step
Epoch 4/30
210/210 - 0s - loss: 0.2576 - accuracy: 0.9348 - 368ms/epoch - 2ms/step
Epoch 5/30
210/210 - 0s - loss: 0.2565 - accuracy: 0.9352 - 397ms/epoch - 2ms/step
Epoch 6/30
210/210 - 0s - loss: 0.2554 - accuracy: 0.9338 - 389ms/epoch - 2ms/step
Epoch 7/30
210/210 - 0s - loss: 0.2544 - accuracy: 0.9352 - 424ms/epoch - 2ms/step
Epoch 8/30
210/210 - 0s - loss: 0.2532 - accuracy: 0.9386 - 394ms/epoch - 2ms/step
Epoch 9/30
210/210 - 0s - loss: 0.2527 - accuracy: 0.9352 - 436ms/epoch - 2ms/step
Epoch 10/30
210/210 - 1s - loss: 0.2518 - accuracy: 0.9352 - 529ms/epoch - 3ms/step
Epoch 11/30
210/210 - 0s - loss: 0.2509 - accuracy: 0.9352 - 404ms/epoch - 2ms/step
Epoch 12/30
210/210 - 0s - loss: 0.2502 - accuracy: 0.9376 - 381ms/epoch - 2ms/step
E

In [43]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30,shuffle=True,verbose=2,validation_split=.1)

Epoch 1/30
189/189 - 1s - loss: 0.2381 - accuracy: 0.9466 - val_loss: 0.2712 - val_accuracy: 0.9286 - 651ms/epoch - 3ms/step
Epoch 2/30
189/189 - 0s - loss: 0.2377 - accuracy: 0.9476 - val_loss: 0.2711 - val_accuracy: 0.9286 - 385ms/epoch - 2ms/step
Epoch 3/30
189/189 - 0s - loss: 0.2373 - accuracy: 0.9476 - val_loss: 0.2711 - val_accuracy: 0.9286 - 418ms/epoch - 2ms/step
Epoch 4/30
189/189 - 0s - loss: 0.2371 - accuracy: 0.9476 - val_loss: 0.2706 - val_accuracy: 0.9286 - 392ms/epoch - 2ms/step
Epoch 5/30
189/189 - 0s - loss: 0.2368 - accuracy: 0.9476 - val_loss: 0.2708 - val_accuracy: 0.9286 - 431ms/epoch - 2ms/step
Epoch 6/30
189/189 - 0s - loss: 0.2364 - accuracy: 0.9444 - val_loss: 0.2714 - val_accuracy: 0.9286 - 415ms/epoch - 2ms/step
Epoch 7/30
189/189 - 0s - loss: 0.2362 - accuracy: 0.9476 - val_loss: 0.2705 - val_accuracy: 0.9286 - 381ms/epoch - 2ms/step
Epoch 8/30
189/189 - 0s - loss: 0.2359 - accuracy: 0.9476 - val_loss: 0.2701 - val_accuracy: 0.9286 - 388ms/epoch - 2ms/step


# predict

In [55]:

# DATA SET GENERATION
test_labels = []
test_samples= []

# total 2100 candidates 

for i in range(50):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)# 1 for sideeffect

    random_older= randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)# 0 for not sideeffect


for i in range(1000):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)# 1 for sideeffect

    random_older= randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)# 0 for not sideeffect


test_samples=np.array(test_samples)
test_labels=np.array(test_labels)
test_samples,test_labels=shuffle(test_samples,test_labels)

scaled_test_samples=scaler.fit_transform(test_samples.reshape(-1,1))

# scaled_text_samples=scaler.fit_transform(x=test_samples,batch_size=10,verbose=1)

In [56]:
predictions= model.predict(x=scaled_test_samples,batch_size=10,verbose=0)

In [64]:
# for i in predictions:
#     print(i)

rounded_predictions=np.argmax(predictions,axis=-1)
for i in range(0,len(rounded_predictions)):
    print(test_samples[i],rounded_predictions[i])

33 0
97 1
95 1
49 0
80 1
65 1
86 1
40 0
94 1
42 0
92 1
93 1
39 0
48 0
100 1
82 1
78 1
69 1
79 1
60 0
16 0
85 1
63 0
34 0
29 0
57 0
23 0
53 0
95 1
85 1
18 0
35 0
67 1
82 1
69 1
98 1
56 0
83 1
34 0
96 1
31 0
90 1
37 0
26 0
18 0
80 1
18 0
30 0
37 0
52 0
31 0
18 0
100 1
57 0
89 1
86 1
95 1
73 1
62 0
28 0
73 1
27 0
58 0
66 1
55 0
74 1
63 0
76 1
78 1
40 0
49 0
52 0
66 1
96 1
66 1
28 0
67 1
73 1
33 0
50 0
73 1
29 0
100 1
51 0
22 0
24 0
78 1
85 1
82 1
53 0
50 0
90 1
60 0
77 1
82 1
39 0
33 0
60 0
29 0
69 1
20 0
26 0
72 1
76 1
40 0
97 1
57 0
82 1
89 1
93 1
80 1
62 0
20 0
92 1
52 0
51 0
52 0
60 0
79 1
58 0
23 0
99 1
74 1
43 0
41 0
95 1
42 0
44 0
27 0
77 1
13 0
61 0
46 0
89 1
33 0
22 0
55 0
35 0
25 0
21 0
82 1
53 0
81 1
15 0
82 1
94 1
93 1
46 0
31 0
14 0
40 0
85 1
30 0
98 1
20 0
43 0
52 0
30 0
22 0
89 1
83 1
65 1
57 0
71 1
81 1
37 0
98 1
14 0
48 0
81 1
59 0
30 0
41 0
72 1
31 0
80 1
56 0
17 0
25 0
26 0
38 0
89 1
47 0
14 0
73 1
88 1
39 0
75 1
51 0
71 1
72 1
26 0
45 0
29 0
19 0
50 0
57 0
89 1
80 1
69

# Confusion Matrix 

In [81]:

cm=[[0,0],[0,0]]
for i in range(0,len(test_labels)):
    a= test_labels[i]
    b=rounded_predictions[i]
    for x in [0,1]:
        for y in [0,1]:
            if a==x:
                if b==y:
                    cm[x][y]+=1

cm

[[983, 67], [49, 1001]]

# Save Model

In [84]:
import os
modelFilename="savedModle/medicalTrial.h5"
if os.path.isfile(modelFilename) is False:
    model.save(modelFilename)

In [86]:
from tensorflow.keras.models import load_model

newModel=load_model(modelFilename)
newModel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [91]:
newModel.get_weights()

[array([[ 0.7151995 , -0.13638952, -0.09046338, -0.35453933, -0.31301296,
         -0.24342737, -0.28232375, -0.37493122, -0.1036523 ,  0.8236849 ,
         -0.4241662 , -0.5639091 , -0.4993934 , -0.4578221 , -0.5734022 ,
         -0.32550195]], dtype=float32),
 array([-0.17948021,  0.        ,  0.30959484,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.18615906,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ], dtype=float32),
 array([[-0.26652724, -0.27414265,  0.58537734, -0.42823946, -0.19001071,
          0.08136902, -0.23982066,  0.14570066,  0.01650959, -0.22200263,
         -0.03744006,  0.65922815,  0.6081334 , -0.1036275 ,  0.44940403,
         -0.18340757, -0.31566143,  0.6063569 ,  0.6386012 ,  0.36387163,
         -0.11739787, -0.46694362,  0.6772772 ,  0.3676449 , -0.24439481,
          0.65488756,  0.49778914, -0.31723604,  0.60442734, -0.11551353,
         -0.6115764 , -0.36674556],
 

In [90]:
newModel.optimizer

In [99]:
from tensorflow.keras.models import model_from_yaml,model_from_json
yamlString=newModel.to_json()
yamlString


modelFromJson=model_from_json(yamlString)
modelFromJson.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [106]:
# newModel.save_weights("modelWeight/weight.h5")
model.get_weights()
model.save_weights("weights.h5")